### PR TITLE
chore: Update README with new setup instructions

### PR DESCRIPTION
**Pull request by chookity-pokk**
This is mentioned in #154 and I figured it was probably a good idea to get this in the official README. All credit goes to 
@Arnavion

### CODE REVIEW

**Comment by chookity-pokk** [comment]
Closes #154

**Comment by chookity-pokk** [comment]
Since this is just a documentation change I am going to merge without review.

**Comment by Arnavion** [comment]
You may want to keep the `code fences` because they make it clear where a command or command arg starts and ends.

**Comment by chookity-pokk** [comment]
> You may want to keep the `code fences` because they make it clear where a command or command arg starts and ends.

@Arnavion Well shucks, looks like I should have waited for a review, so embarrassing. Thanks, I'll open a PR later adding those in.

**Pull request merged**
